# Ahoy configuration file.
# http://www.ahoycli.com/
---
ahoyapi: v2

commands:

  build:
    usage: Build or rebuild the project.
    cmd: |
      ahoy build-codebase
      ahoy start-server
      ahoy provision

  build-codebase:
    usage: Build the codebase.
    cmd: ./.devtools/build-codebase.sh

  start-server:
    usage: Start built-in PHP-server.
    cmd: ./.devtools/start-server.sh

  provision:
    usage: Provision a website.
    cmd: ./.devtools/provision.sh

  drush:
    usage: Run Drush command.
    cmd: build/vendor/bin/drush -l http://${WEBSERVER_HOST:-localhost}:${WEBSERVER_PORT:-8000} $*

  login:
    usage: Login to a website.
    cmd: ahoy drush uli

  lint:
    usage: Lint code.
    cmd: |
      pushd "build" >/dev/null || exit 1
      vendor/bin/phpcs
      vendor/bin/phpstan
      vendor/bin/rector --clear-cache --dry-run
      vendor/bin/phpmd . text phpmd.xml
      vendor/bin/twig-cs-fixer
      popd >/dev/null || exit 1

  lint-fix:
    usage: Fix coding standards.
    cmd: |
      pushd "build" >/dev/null || exit 1
      vendor/bin/rector --clear-cache
      vendor/bin/phpcbf
      popd >/dev/null || exit 1

  test:
    usage: Run all tests.
    cmd: |
      pushd "build" >/dev/null || exit 1
      vendor/bin/phpunit
      popd >/dev/null || exit 1

  test-unit:
    usage: Run unit tests.
    cmd: |
      pushd "build" >/dev/null || exit 1
      vendor/bin/phpunit --testsuite unit
      popd >/dev/null || exit 1

  test-kernel:
    usage: Run kernel tests.
    cmd: |
      pushd "build" >/dev/null || exit 1
      vendor/bin/phpunit --testsuite kernel
      popd >/dev/null || exit 1

  test-functional:
    usage: Run functional tests.
    cmd: |
      pushd "build" >/dev/null || exit 1
      vendor/bin/phpunit --testsuite functional
      popd >/dev/null || exit 1

  reset:
    usage: Reset the project.
    cmd: |
      killall -9 php >/dev/null 2>&1 || true
      chmod -Rf 777 build > /dev/null
      rm -Rf build > /dev/null || true
      rm -Rf .logs > /dev/null || true

# Override entrypoint to alter default behaviour of Ahoy.
entrypoint:
  - bash
  - -c
  - -e
  - |
    extension="$(basename -s .info.yml -- ./*.info.yml)"
    export SIMPLETEST_BASE_URL=http://${WEBSERVER_HOST:-localhost}:${WEBSERVER_PORT:-8000}
    export SIMPLETEST_DB=sqlite://localhost/drupal_test_${extension}.sqlite
    bash -e -c "$0" "$@"
  - '{{cmd}}'
  - '{{name}}'
